version: '3.5'
services:

  reels:
    build: .
#      context: .
#      dockerfile: reels.dockerfile
    #    image: &app pegasus
    restart: "no"
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    env_file: &envfile
      - env.env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - broker
      - db

  worker:
    build: .
#    image: *app
    restart: "no"
    env_file:
      - env.env
    command: celery -A pegasus worker -l info
    volumes:
      - .:/code
    depends_on:
      - broker

  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    restart: "no"
    env_file:
      - env.env
    ports:
      - "5555:5555"
    depends_on:
      - broker
      - worker

  broker:
    image: rabbitmq:3.8.9
#    command:
    env_file:
      - env.env
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: postgres
    env_file:
      - env.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - env.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data: