version: '3.5'

volumes:
  media-data:
    driver: azure_file
    driver_opts:
      share_name: mediashare
      storage_account_name: pegasuspietelitestorage
  db-data:
    driver: azure_file
    driver_opts:
      share_name: dbshare
      storage_account_name: pegasuspietelitestorage
  pgadmin-data:
    driver: azure_file
    driver_opts:
      share_name: pgadminshare
      storage_account_name: pegasuspietelitestorage
  mongo-express-data:
    driver: azure_file
    driver_opts:
      share_name: mongoexpressshare
      storage_account_name: pegasuspietelitestorage

#networks:
#  pegasus-net:
##    driver: azure-vnet
##    driver_opts:
##      ipam-driver: azure-vnet
##      subnet: pegasusacisubnet